name: Setup & build calm-dsl
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Print python version
      run: echo ${{ steps.setup-python.outputs.python-version }}
    - name: black
      if: startsWith(steps.setup-python.outputs.python-version, '3.7')
      uses: psf/black@stable # Exclude list is not honored - https://github.com/psf/black/issues/1584
      with:
        version: "22.6.0"
        options: "--check --extend-exclude tests/escript/scripts/"
    - name: Setup env
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
    - name: Install requirements
      run: |
        make dev
