name: run pre commit tests
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: black
        uses: psf/black@stable
        with:
          version: "22.6.0"
          options: "--check --extend-exclude tests/escript/scripts/"
      - name: Setup env
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
      - name: Install requirements
        run: |
          make dev
      - name: Set environment variables
        shell: bash
        run: |
          value="MOCK"
          echo "CALM_DSL_TESTS=$value" >> $GITHUB_ENV
          echo "${{ env.CALM_DSL_TESTS }}"
      - name: Build test environment
        run: |
          source venv/bin/activate
          calm --version
          pytest --version
          cd tests/mock && make mock-db-location && make mock-db
      - name: Run Tests and Calculate Coverage
        run: |
          source venv/bin/activate
          echo "python_files = tests/unit/test_calm_ref.py" >> pytest.ini
          pytest -m pre_commit
          coverage_percentage=$(coverage report -m | awk '/calm\/dsl\/builtins\/models\/calm_ref.py/ {print $6}')
          echo "Coverage Percentage: $coverage_percentage%"
          coverage=$(echo "$coverage_percentage" | sed 's/%//')
          if [ "$coverage" -lt 40 ]; then
            echo "Code coverage is below the threshold (40%). Blocking PR."
            exit 1
          fi
        env:
          CI: true
