name: run pre commit tests
on:
  workflow_dispatch
env: 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: black
        uses: psf/black@stable
        with:
          version: "22.6.0"
          options: "--check --extend-exclude tests/escript/scripts/"
      - name: Setup env
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
      - name: Install requirements
        run: |
          make dev
      - name: Build test environment
        run: |
          pwd
          source venv/bin/activate
          calm --version
          pytest --version
          python tests/unit/update_init.py
          pwd
          pytest "tests/unit/test_calm_ref.py"